"""Step 24z: Aggregate Fig 3H multi-cohort treatment validation summary.

Reads per-cohort outputs in fig_treatment/ and writes:
  treatment_validation_summary.csv  (long: cohort × score × stat)
  treatment_validation_summary.md   (narrative)
"""
from __future__ import annotations
import os, sys
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
sys.path.insert(0, str(os.path.expanduser("~/luad/scripts")))
from pathlib import Path
import numpy as np
import pandas as pd
from importlib import import_module
C = import_module("24_common")

OUT = C.OUT


def load_io(gse: str, treatment_label: str) -> pd.DataFrame:
    """Standard 24-style file (preferred); fallback to legacy GSE207422 format."""
    f = OUT / f"{gse}_response_comparison.csv"
    if f.exists():
        df = pd.read_csv(f)
    else:
        # Legacy GSE207422 file: gse207422_mpr_vs_nmpr.csv (subset=all)
        legacy = OUT / f"{gse}_mpr_vs_nmpr.csv"
        if not legacy.exists():
            return pd.DataFrame()
        df = pd.read_csv(legacy)
        df = df[df["subset"] == "all"].copy()
        df = df.rename(columns={"n_mpr": "n_pos", "n_nmpr": "n_neg",
                                  "median_mpr": "median_pos",
                                  "median_nmpr": "median_neg",
                                  "auc_mpr_predict": "auc"})
        df["pos_group"] = "MPR"; df["neg_group"] = "NMPR"
    df["cohort"] = gse.upper()
    df["analysis_type"] = "IO_R_vs_NR"
    df["treatment_label"] = treatment_label
    return df


def load_act(gse: str, treatment_label: str) -> pd.DataFrame:
    f = OUT / f"{gse}_response_comparison.csv"
    if not f.exists():
        return pd.DataFrame()
    df = pd.read_csv(f)
    df["cohort"] = gse.upper()
    df["analysis_type"] = "ACT_Cox_interaction"
    df["treatment_label"] = treatment_label
    return df


def main():
    C.log("aggregating Fig 3H summary")

    # IO cohorts (R vs NR Wilcoxon + AUC)
    io_207422 = load_io("gse207422", "neoadj chemo-IO 24 NSCLC")
    io_126044 = load_io("gse126044", "anti-PD-1 16 NSCLC")
    io_135222 = load_io("gse135222", "anti-PD-1/L1 27 NSCLC (DCB ≥180d)")

    io_combined = pd.concat([io_207422, io_126044, io_135222],
                              ignore_index=True, sort=False)

    # ACT cohorts (Cox interaction)
    act_14814 = load_act("gse14814", "JBR.10 ACT 133 NSCLC")
    act_42127 = load_act("gse42127", "UT SPORE ACT 176 NSCLC (133 ADC)")
    act_combined = pd.concat([act_14814, act_42127],
                                ignore_index=True, sort=False)

    # Pretty long-format summary CSV
    long_rows = []
    for _, r in io_combined.iterrows():
        # io has columns: score, n_pos, n_neg, median_pos, median_neg, p, auc, ...
        long_rows.append({
            "cohort": r["cohort"], "treatment": r.get("treatment_label", ""),
            "analysis_type": "IO",
            "score": r["score"],
            "n": int(r["n_pos"] + r["n_neg"]),
            "median_R": r["median_pos"],
            "median_NR": r["median_neg"],
            "delta": r["delta"],
            "wilcoxon_p": r["p"],
            "auc": r["auc"],
            "subset": "all",
            "interaction_p": np.nan,
            "interaction_hr": np.nan,
            "hr_act_in_high": np.nan,
            "hr_act_in_low": np.nan,
        })
    for _, r in act_combined.iterrows():
        long_rows.append({
            "cohort": r["cohort"], "treatment": r.get("treatment_label", ""),
            "analysis_type": "ACT",
            "score": r["score"],
            "n": int(r["n"]),
            "median_R": np.nan,
            "median_NR": np.nan,
            "delta": np.nan,
            "wilcoxon_p": np.nan,
            "auc": np.nan,
            "subset": r["subset"],
            "interaction_p": r["interaction_p"],
            "interaction_hr": r["interaction_hr"],
            "hr_act_in_high": r["hr_act_in_mp_high"],
            "hr_act_in_low": r["hr_act_in_mp_low"],
        })
    summary = pd.DataFrame(long_rows)
    summary.to_csv(OUT / "treatment_validation_summary.csv", index=False)
    C.log(f"summary rows: {len(summary)}")

    # MP1-4 only narrative table
    md_lines = []
    md_lines.append("# Fig 3H — Multi-cohort treatment validation summary\n")
    md_lines.append("Generated by `scripts/24z_summary.py` from per-cohort outputs in `fig_treatment/`.\n")

    # IO MP1-4 table
    io_mp = summary[(summary["analysis_type"]=="IO")
                     & (summary["score"].isin(["MP1","MP2","MP3","MP4"]))]
    io_pivot = io_mp.pivot_table(index="cohort", columns="score",
                                    values="auc", aggfunc="first").round(3)
    io_p = io_mp.pivot_table(index="cohort", columns="score",
                                values="wilcoxon_p", aggfunc="first").round(4)
    md_lines.append("## Immunotherapy cohorts — AUC (R vs NR)\n")
    md_lines.append("AUC > 0.5 means score is HIGHER in responders.\n\n")
    md_lines.append(io_pivot.to_markdown())
    md_lines.append("\n\n## Immunotherapy cohorts — Wilcoxon p\n\n")
    md_lines.append(io_p.to_markdown())
    md_lines.append("\n\n")

    # ACT MP1-4 table — interaction p (subset=all_nsclc)
    act_mp = summary[(summary["analysis_type"]=="ACT")
                       & (summary["subset"]=="all_nsclc")
                       & (summary["score"].isin(["MP1","MP2","MP3","MP4"]))]
    act_p = act_mp.pivot_table(index="cohort", columns="score",
                                  values="interaction_p", aggfunc="first").round(4)
    act_hr_high = act_mp.pivot_table(index="cohort", columns="score",
                                          values="hr_act_in_high",
                                          aggfunc="first").round(3)
    act_hr_low = act_mp.pivot_table(index="cohort", columns="score",
                                         values="hr_act_in_low",
                                         aggfunc="first").round(3)
    md_lines.append("## Adjuvant chemo cohorts — Cox MP × ACT interaction (all-NSCLC)\n\n")
    md_lines.append("**Interaction p-value (MP_z × treatment):**\n")
    md_lines.append(act_p.to_markdown())
    md_lines.append("\n\n**HR(ACT vs OBS) in MP-HIGH:**\n")
    md_lines.append(act_hr_high.to_markdown())
    md_lines.append("\n\n**HR(ACT vs OBS) in MP-LOW:**\n")
    md_lines.append(act_hr_low.to_markdown())
    md_lines.append("\n\nHR < 1 means ACT benefits OS in that subgroup. "
                     "If HR(MP-high) << HR(MP-low), MP-high preferentially benefits.\n\n")

    # ADC subset (chemo)
    act_mp_adc = summary[(summary["analysis_type"]=="ACT")
                            & (summary["subset"]=="ADC_only")
                            & (summary["score"].isin(["MP1","MP2","MP3","MP4"]))]
    if len(act_mp_adc):
        adc_p = act_mp_adc.pivot_table(index="cohort", columns="score",
                                            values="interaction_p",
                                            aggfunc="first").round(4)
        adc_hh = act_mp_adc.pivot_table(index="cohort", columns="score",
                                              values="hr_act_in_high",
                                              aggfunc="first").round(3)
        adc_hl = act_mp_adc.pivot_table(index="cohort", columns="score",
                                              values="hr_act_in_low",
                                              aggfunc="first").round(3)
        md_lines.append("## Adjuvant chemo — ADC subset only\n\n")
        md_lines.append("**Interaction p:**\n" + adc_p.to_markdown() + "\n\n")
        md_lines.append("**HR(ACT) MP-high:**\n" + adc_hh.to_markdown() + "\n\n")
        md_lines.append("**HR(ACT) MP-low:**\n" + adc_hl.to_markdown() + "\n\n")

    # Skipped / metadata-only
    md_lines.append("## Skipped / metadata-only\n\n")
    md_lines.append("- **GSE93157** (NanoString 730-gene, n=35 NSCLC subset): SKIPPED. "
                     "MP top-50 overlap < 15/50 for all 4 MPs (max 11/50 for MP1). "
                     "See `gse93157_mp_panel_overlap.csv`.\n")
    md_lines.append("- **GSE243013** (scRNA chemo-IO, n=243): metadata-only. "
                     "Counts mtx (6.6 GB) not downloaded; immune-cell scRNA "
                     "(no malignant cells) → MP1-4 not scoreable. "
                     "Cell-type composition vs response in "
                     "`gse243013_response_celltype_compare.csv`.\n\n")

    # Cohort table
    md_lines.append("## Cohorts overview\n\n")
    md_lines.append("| Cohort | Treatment | n | Platform | Analysis |\n")
    md_lines.append("|--------|-----------|---|----------|----------|\n")
    md_lines.append("| GSE207422 | neoadj chemo-IO | 24 NSCLC | bulk RNA-seq | MPR vs NMPR |\n")
    md_lines.append("| GSE126044 | anti-PD-1 | 16 NSCLC | bulk RNA-seq | R vs NR |\n")
    md_lines.append("| GSE135222 | anti-PD-1/L1 | 27 NSCLC | bulk RNA-seq | DCB ≥180d vs <180d |\n")
    md_lines.append("| GSE93157  | Pembro/Nivo | 35 NSCLC subset | NanoString 730 | SKIPPED (overlap <15/50) |\n")
    md_lines.append("| GSE14814  | adjuvant chemo (JBR.10) | 133 NSCLC | Affy U133A | Cox MP×ACT |\n")
    md_lines.append("| GSE42127  | adjuvant chemo (UT SPORE) | 176 NSCLC (133 ADC) | Illumina BeadChip | Cox MP×ACT |\n")
    md_lines.append("| GSE243013 | neoadj chemo-IO | 243 NSCLC | scRNA-seq | metadata-only |\n\n")

    (OUT / "treatment_validation_summary.md").write_text(
        "\n".join(md_lines), encoding="utf-8")
    C.log(f"wrote {OUT/'treatment_validation_summary.md'}")
    C.log(f"wrote {OUT/'treatment_validation_summary.csv'}")


if __name__ == "__main__":
    main()
